package com.dlnu.pojo;

// Generated 2014-6-26 13:39:02 by Hibernate Tools 3.4.0.CR1


/**
 * Card generated by hbm2java
 */
public class Card implements java.io.Serializable {

	private Integer cardid;
	private Cardfloder cardfloder;
	private String cname;
	private String dept;
	private String position;
	private String tel;
	private String phone;
	private String email;

	public Card() {
	}

	public Card(Integer cardid, String tel, String phone, String email) {
		this.cardid = cardid;
		this.tel = tel;
		this.phone = phone;
		this.email = email;
	}

	public Card(Integer cardid, Cardfloder cardfloder, String cname,
			String dept, String position, String tel, String phone, String email) {
		this.cardid = cardid;
		this.cardfloder = cardfloder;
		this.cname = cname;
		this.dept = dept;
		this.position = position;
		this.tel = tel;
		this.phone = phone;
		this.email = email;
	}

	public Integer getCardid() {
		return this.cardid;
	}

	public void setCardid(Integer cardid) {
		this.cardid = cardid;
	}

	public Cardfloder getCardfloder() {
		return this.cardfloder;
	}

	public void setCardfloder(Cardfloder cardfloder) {
		this.cardfloder = cardfloder;
	}

	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	public String getDept() {
		return this.dept;
	}

	public void setDept(String dept) {
		this.dept = dept;
	}

	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
