package com.dlnu.pojo;

// Generated 2014-6-26 13:39:02 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Cardfloder generated by hbm2java
 */
public class Cardfloder implements java.io.Serializable {

	private Integer cid;
	private Users users;
	private String cname;
	private Set cards = new HashSet(0);

	public Cardfloder() {
	}

	public Cardfloder(Integer cid, String cname) {
		this.cid = cid;
		this.cname = cname;
	}

	public Cardfloder(Integer cid, Users users, String cname, Set cards) {
		this.cid = cid;
		this.users = users;
		this.cname = cname;
		this.cards = cards;
	}

	public Integer getCid() {
		return this.cid;
	}

	public void setCid(Integer cid) {
		this.cid = cid;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	public Set getCards() {
		return this.cards;
	}

	public void setCards(Set cards) {
		this.cards = cards;
	}

}
