package com.dlnu.pojo;

// Generated 2014-6-26 13:39:02 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Department generated by hbm2java
 */
public class Department implements java.io.Serializable {

	private Integer did;
	private String dname;
	private String phone;
	private String function;
	private Set userses = new HashSet(0);

	public Department() {
	}

	public Department(Integer did, String dname, String phone,
			String function) {
		this.did = did;
		this.dname = dname;
		this.phone = phone;
		this.function = function;
	}

	public Department(Integer did, String dname, String phone,
			String function, Set userses) {
		this.did = did;
		this.dname = dname;
		this.phone = phone;
		this.function = function;
		this.userses = userses;
	}

	public Integer getDid() {
		return this.did;
	}

	public void setDid(Integer did) {
		this.did = did;
	}

	public String getDname() {
		return this.dname;
	}

	public void setDname(String dname) {
		this.dname = dname;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getFunction() {
		return this.function;
	}

	public void setFunction(String function) {
		this.function = function;
	}

	public Set getUserses() {
		return this.userses;
	}

	public void setUserses(Set userses) {
		this.userses = userses;
	}

}
