package com.dlnu.pojo;

// Generated 2014-6-26 13:39:02 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Floder generated by hbm2java
 */
public class Floder implements java.io.Serializable {

	private Integer fid;
	private Users users;
	private String fname;
	private Integer fatherfid;
	private Set fileses = new HashSet(0);

	public Floder() {
	}

	public Floder(Integer fid, String fname) {
		this.fid = fid;
		this.fname = fname;
	}

	public Floder(Integer fid, Users users, String fname,
			Integer fatherfid, Set fileses) {
		this.fid = fid;
		this.users = users;
		this.fname = fname;
		this.fatherfid = fatherfid;
		this.fileses = fileses;
	}

	public Integer getFid() {
		return this.fid;
	}

	public void setFid(Integer fid) {
		this.fid = fid;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public Integer getFatherfid() {
		return this.fatherfid;
	}

	public void setFatherfid(Integer fatherfid) {
		this.fatherfid = fatherfid;
	}

	public Set getFileses() {
		return this.fileses;
	}

	public void setFileses(Set fileses) {
		this.fileses = fileses;
	}

}
