package com.dlnu.pojo;

// Generated 2014-6-26 13:39:02 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Message generated by hbm2java
 */
public class Message implements java.io.Serializable {

	private Integer messid;
	private String title;
	private String content;
	private Date time;
	private Set usersMessages = new HashSet(0);

	public Message() {
	}

	public Message(Integer messid) {
		this.messid = messid;
	}

	public Message(Integer messid, String title, String content, Date time,
			Set usersMessages) {
		this.messid = messid;
		this.title = title;
		this.content = content;
		this.time = time;
		this.usersMessages = usersMessages;
	}

	public Integer getMessid() {
		return this.messid;
	}

	public void setMessid(Integer messid) {
		this.messid = messid;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public Set getUsersMessages() {
		return this.usersMessages;
	}

	public void setUsersMessages(Set usersMessages) {
		this.usersMessages = usersMessages;
	}

}
