package com.dlnu.pojo;

// Generated 2014-6-26 13:39:02 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Mroom generated by hbm2java
 */
public class Mroom implements java.io.Serializable {

	private Integer mrid;
	private String mname;
	private String mraddress;
	private Integer mrpeople;
	private Integer mracondition;
	private Integer mrprojector;
	private Set usersRooms = new HashSet(0);
	private Set meetings = new HashSet(0);

	public Mroom() {
	}

	public Mroom(Integer mrid, Integer mrpeople, Integer mrprojector) {
		this.mrid = mrid;
		this.mrpeople = mrpeople;
		this.mrprojector = mrprojector;
	}

	public Mroom(Integer mrid, String mname, String mraddress,
			Integer mrpeople, Integer mracondition,
			Integer mrprojector, Set usersRooms, Set meetings) {
		this.mrid = mrid;
		this.mname = mname;
		this.mraddress = mraddress;
		this.mrpeople = mrpeople;
		this.mracondition = mracondition;
		this.mrprojector = mrprojector;
		this.usersRooms = usersRooms;
		this.meetings = meetings;
	}

	public Integer getMrid() {
		return this.mrid;
	}

	public void setMrid(Integer mrid) {
		this.mrid = mrid;
	}

	public String getMname() {
		return this.mname;
	}

	public void setMname(String mname) {
		this.mname = mname;
	}

	public String getMraddress() {
		return this.mraddress;
	}

	public void setMraddress(String mraddress) {
		this.mraddress = mraddress;
	}

	public Integer getMrpeople() {
		return this.mrpeople;
	}

	public void setMrpeople(Integer mrpeople) {
		this.mrpeople = mrpeople;
	}

	public Integer getMracondition() {
		return this.mracondition;
	}

	public void setMracondition(Integer mracondition) {
		this.mracondition = mracondition;
	}

	public Integer getMrprojector() {
		return this.mrprojector;
	}

	public void setMrprojector(Integer mrprojector) {
		this.mrprojector = mrprojector;
	}

	public Set getUsersRooms() {
		return this.usersRooms;
	}

	public void setUsersRooms(Set usersRooms) {
		this.usersRooms = usersRooms;
	}

	public Set getMeetings() {
		return this.meetings;
	}

	public void setMeetings(Set meetings) {
		this.meetings = meetings;
	}

}
