package com.dlnu.pojo;

// Generated 2014-6-26 13:39:02 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Postion generated by hbm2java
 */
public class Postion implements java.io.Serializable {

	private Integer postid;
	private String postname;
	private Set userses = new HashSet(0);

	public Postion() {
	}

	public Postion(Integer postid) {
		this.postid = postid;
	}

	public Postion(Integer postid, String postname, Set userses) {
		this.postid = postid;
		this.postname = postname;
		this.userses = userses;
	}

	public Integer getPostid() {
		return this.postid;
	}

	public void setPostid(Integer postid) {
		this.postid = postid;
	}

	public String getPostname() {
		return this.postname;
	}

	public void setPostname(String postname) {
		this.postname = postname;
	}

	public Set getUserses() {
		return this.userses;
	}

	public void setUserses(Set userses) {
		this.userses = userses;
	}

}
