package com.dlnu.pojo;

// Generated 2014-6-26 13:39:02 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Schedule generated by hbm2java
 */
public class Schedule implements java.io.Serializable {

	private Integer hid;
	private String sname;
	private Date starttime;
	private Date endtime;
	private String content;
	private Set userSchedules = new HashSet(0);

	public Schedule() {
	}

	public Schedule(String sname, Date starttime, Date endtime, String content) {
		this.sname = sname;
		this.starttime = starttime;
		this.endtime = endtime;
		this.content = content;
	}

	public Schedule(Integer hid, String content) {
		this.hid = hid;
		this.content = content;
	}

	public Schedule(Integer hid, String sname, Date starttime, Date endtime,
			String content, Set userSchedules) {
		this.hid = hid;
		this.sname = sname;
		this.starttime = starttime;
		this.endtime = endtime;
		this.content = content;
		this.userSchedules = userSchedules;
	}

	public Integer getHid() {
		return this.hid;
	}

	public void setHid(Integer hid) {
		this.hid = hid;
	}

	public String getSname() {
		return this.sname;
	}

	public void setSname(String sname) {
		this.sname = sname;
	}

	public Date getStarttime() {
		return this.starttime;
	}

	public void setStarttime(Date starttime) {
		this.starttime = starttime;
	}

	public Date getEndtime() {
		return this.endtime;
	}

	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Set getUserSchedules() {
		return this.userSchedules;
	}

	public void setUserSchedules(Set userSchedules) {
		this.userSchedules = userSchedules;
	}

}
