package com.dlnu.pojo;

// Generated 2014-6-26 13:39:02 by Hibernate Tools 3.4.0.CR1


/**
 * UserMeeting generated by hbm2java
 */
public class UserMeeting implements java.io.Serializable {

	private Integer umeetid;
	private Users users;
	private Meeting meeting;

	public UserMeeting() {
	}

	public UserMeeting(Integer umeetid, Users users, Meeting meeting) {
		this.umeetid = umeetid;
		this.users = users;
		this.meeting = meeting;
	}

	public Integer getUmeetid() {
		return this.umeetid;
	}

	public void setUmeetid(Integer umeetid) {
		this.umeetid = umeetid;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Meeting getMeeting() {
		return this.meeting;
	}

	public void setMeeting(Meeting meeting) {
		this.meeting = meeting;
	}

}
