package com.dlnu.pojo;

// Generated 2014-6-26 13:39:02 by Hibernate Tools 3.4.0.CR1


/**
 * UserSchedule generated by hbm2java
 */
public class UserSchedule implements java.io.Serializable {

	private Integer uscheid;
	private Users usersByActorid;
	private Users usersByPlanid;
	private Schedule schedule;

	public UserSchedule() {
	}

	public UserSchedule(Integer uscheid, Users usersByPlanid,
			Schedule schedule) {
		this.uscheid = uscheid;
		this.usersByPlanid = usersByPlanid;
		this.schedule = schedule;
	}

	public UserSchedule(Integer uscheid, Users usersByActorid,
			Users usersByPlanid, Schedule schedule) {
		this.uscheid = uscheid;
		this.usersByActorid = usersByActorid;
		this.usersByPlanid = usersByPlanid;
		this.schedule = schedule;
	}

	public Integer getUscheid() {
		return this.uscheid;
	}

	public void setUscheid(Integer uscheid) {
		this.uscheid = uscheid;
	}

	public Users getUsersByActorid() {
		return this.usersByActorid;
	}

	public void setUsersByActorid(Users usersByActorid) {
		this.usersByActorid = usersByActorid;
	}

	public Users getUsersByPlanid() {
		return this.usersByPlanid;
	}

	public void setUsersByPlanid(Users usersByPlanid) {
		this.usersByPlanid = usersByPlanid;
	}

	public Schedule getSchedule() {
		return this.schedule;
	}

	public void setSchedule(Schedule schedule) {
		this.schedule = schedule;
	}

}
