package com.dlnu.pojo;

// Generated 2014-6-26 13:39:02 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * UsersRoom generated by hbm2java
 */
public class UsersRoom implements java.io.Serializable {

	private Integer uroomid;
	private Users users;
	private Mroom mroom;
	private Date starttime;
	private Date endtime;

	public UsersRoom() {
	}

	public UsersRoom(Integer uroomid, Users users, Mroom mroom) {
		this.uroomid = uroomid;
		this.users = users;
		this.mroom = mroom;
	}

	public UsersRoom(Integer uroomid, Users users, Mroom mroom,
			Date starttime, Date endtime) {
		this.uroomid = uroomid;
		this.users = users;
		this.mroom = mroom;
		this.starttime = starttime;
		this.endtime = endtime;
	}

	public Integer getUroomid() {
		return this.uroomid;
	}

	public void setUroomid(Integer uroomid) {
		this.uroomid = uroomid;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Mroom getMroom() {
		return this.mroom;
	}

	public void setMroom(Mroom mroom) {
		this.mroom = mroom;
	}

	public Date getStarttime() {
		return this.starttime;
	}

	public void setStarttime(Date starttime) {
		this.starttime = starttime;
	}

	public Date getEndtime() {
		return this.endtime;
	}

	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}

}
