package com.dlnu.pojo;

// Generated 2014-6-26 13:39:02 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private Integer userid;
	private Department department;
	private Postion postion;
	private String uname;
	private String upass;
	private String name;
	private String sex;
	private Byte age;
	private String email;
	private String tel;
	private String phone;
	private String address;
	private String interest;
	private String introduce;
	private Set usersMessagesForReceiveid = new HashSet(0);
	private Set userSchedulesForActorid = new HashSet(0);
	private Set usersRoles = new HashSet(0);
	private Set userSchedulesForPlanid = new HashSet(0);
	private Set cardfloders = new HashSet(0);
	private Set usersRooms = new HashSet(0);
	private Set usersMessagesForSendid = new HashSet(0);
	private Set floders = new HashSet(0);
	private Set userMeetings = new HashSet(0);

	public Users() {
	}

	public Users(Integer userid, String uname, String upass, String email,
			String tel, String address, String interest, String introduce) {
		this.userid = userid;
		this.uname = uname;
		this.upass = upass;
		this.email = email;
		this.tel = tel;
		this.address = address;
		this.interest = interest;
		this.introduce = introduce;
	}

	public Users(Integer userid, Department department, Postion postion,
			String uname, String upass, String name, String sex, Byte age,
			String email, String tel, String phone, String address,
			String interest, String introduce, Set usersMessagesForReceiveid,
			Set userSchedulesForActorid, Set usersRoles,
			Set userSchedulesForPlanid, Set cardfloders, Set usersRooms,
			Set usersMessagesForSendid, Set floders, Set userMeetings) {
		this.userid = userid;
		this.department = department;
		this.postion = postion;
		this.uname = uname;
		this.upass = upass;
		this.name = name;
		this.sex = sex;
		this.age = age;
		this.email = email;
		this.tel = tel;
		this.phone = phone;
		this.address = address;
		this.interest = interest;
		this.introduce = introduce;
		this.usersMessagesForReceiveid = usersMessagesForReceiveid;
		this.userSchedulesForActorid = userSchedulesForActorid;
		this.usersRoles = usersRoles;
		this.userSchedulesForPlanid = userSchedulesForPlanid;
		this.cardfloders = cardfloders;
		this.usersRooms = usersRooms;
		this.usersMessagesForSendid = usersMessagesForSendid;
		this.floders = floders;
		this.userMeetings = userMeetings;
	}

	public Integer getUserid() {
		return this.userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	public Department getDepartment() {
		return this.department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	public Postion getPostion() {
		return this.postion;
	}

	public void setPostion(Postion postion) {
		this.postion = postion;
	}

	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	public String getUpass() {
		return this.upass;
	}

	public void setUpass(String upass) {
		this.upass = upass;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public Byte getAge() {
		return this.age;
	}

	public void setAge(Byte age) {
		this.age = age;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getInterest() {
		return this.interest;
	}

	public void setInterest(String interest) {
		this.interest = interest;
	}

	public String getIntroduce() {
		return this.introduce;
	}

	public void setIntroduce(String introduce) {
		this.introduce = introduce;
	}

	public Set getUsersMessagesForReceiveid() {
		return this.usersMessagesForReceiveid;
	}

	public void setUsersMessagesForReceiveid(Set usersMessagesForReceiveid) {
		this.usersMessagesForReceiveid = usersMessagesForReceiveid;
	}

	public Set getUserSchedulesForActorid() {
		return this.userSchedulesForActorid;
	}

	public void setUserSchedulesForActorid(Set userSchedulesForActorid) {
		this.userSchedulesForActorid = userSchedulesForActorid;
	}

	public Set getUsersRoles() {
		return this.usersRoles;
	}

	public void setUsersRoles(Set usersRoles) {
		this.usersRoles = usersRoles;
	}

	public Set getUserSchedulesForPlanid() {
		return this.userSchedulesForPlanid;
	}

	public void setUserSchedulesForPlanid(Set userSchedulesForPlanid) {
		this.userSchedulesForPlanid = userSchedulesForPlanid;
	}

	public Set getCardfloders() {
		return this.cardfloders;
	}

	public void setCardfloders(Set cardfloders) {
		this.cardfloders = cardfloders;
	}

	public Set getUsersRooms() {
		return this.usersRooms;
	}

	public void setUsersRooms(Set usersRooms) {
		this.usersRooms = usersRooms;
	}

	public Set getUsersMessagesForSendid() {
		return this.usersMessagesForSendid;
	}

	public void setUsersMessagesForSendid(Set usersMessagesForSendid) {
		this.usersMessagesForSendid = usersMessagesForSendid;
	}

	public Set getFloders() {
		return this.floders;
	}

	public void setFloders(Set floders) {
		this.floders = floders;
	}

	public Set getUserMeetings() {
		return this.userMeetings;
	}

	public void setUserMeetings(Set userMeetings) {
		this.userMeetings = userMeetings;
	}

}
