package com.dlnu.pojo;

// Generated 2014-6-26 13:39:02 by Hibernate Tools 3.4.0.CR1


/**
 * UsersRole generated by hbm2java
 */
public class UsersRole implements java.io.Serializable {

	private Integer uroleid;
	private Users users;
	private Role role;

	public UsersRole() {
	}

	public UsersRole(Integer uroleid, Users users, Role role) {
		this.uroleid = uroleid;
		this.users = users;
		this.role = role;
	}

	public Integer getUroleid() {
		return this.uroleid;
	}

	public void setUroleid(Integer uroleid) {
		this.uroleid = uroleid;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

}
